set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'Simple-Javascript-Indenter'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'matchit.zip'
Plugin 'badwolf'
Plugin 'hallison/vim-markdown'
Plugin 'othree/html5.vim'
Plugin 'othree/html5-syntax.vim'
Plugin 'MatchTag'

call vundle#end()            " required
filetype plugin indent on    " required


syntax enable
syntax on
"缩进
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab 
"相对行号
set nu
"自动缩进
set autoindent 
set cindent
"搜索高亮
set hlsearch
"搜索的时候忽略大小写
set ignorecase smartcase
"黑色背景
set background=dark
"禁止产生*.swp文件 这些个东西老是导致watch的时候频繁更新
set noswapfile
"colorscheme monokai
colorscheme badwolf
autocmd InsertLeave * se nocul  
autocmd InsertEnter * se cul
"nerdtree
"autocmd vimenter * NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <silent> <C-t> :NERDTreeToggle<CR>
let NERDTreeShowBookmarks=1  
let g:ctrlp_custom_ignore='\v[\/](node_modules)$' 
filetype on 
filetype plugin on 
filetype indent on
